#!/usr/bin/env python3

#  try:
#          from Xpander import conf, manager, service, XInterface, gtkui
#  except ImportError:
#          Logger.exception('Running from source.')
#          from lib import conf, manager, service, XInterface, gtkui
from lib import app

app.App().start()
